# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: minimal

# Caching so the next build will be fast too.
#cache:
#  directories: []

matrix:
  include:
  - env: PANDOCVERSION=2.0.6
    addons: {apt: {packages: [texlive-bibtex-extra,aspell,aspell-fr,aspell-en]}}
  - env: PANDOCVERSION=2.1
    addons: {apt: {packages: [texlive-bibtex-extra,aspell,aspell-fr,aspell-en]}}

  allow_failures:
  - env: PANDOCVERSION=2.0.6

  fast_finish: true

before_install:
- unset CC
- export PATH=$HOME/pandoc-$PANDOCVERSION/bin:$PATH
# Download and unpack the pandoc binary
- |
  pushd $HOME
  wget https://github.com/jgm/pandoc/releases/download/$PANDOCVERSION/pandoc-$PANDOCVERSION-linux.tar.gz
  tar xvzf pandoc-$PANDOCVERSION-linux.tar.gz
  popd

install: []

script:
- |
  make test

