# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: minimal

addons:
  apt:
    packages:
      - aspell
      - aspell-fr
      - aspell-en
      - imagemagick
      - default-jre
      - latex-xcolor
      - lmodern
      - texlive-bibtex-extra
      - texlive-fonts-recommended
      - texlive-latex-recommended

before_install:
- unset CC
# Download and unpack the pandoc binary
- |
  pushd $HOME
  RELEASES_URL='https://github.com/jgm/pandoc/releases'
  export PANDOCVERSION=$(curl -I "$RELEASES_URL/latest" | sed -ne 's#Location:.*tag/\(.*\)$#\1#p' | tr -d "\n\r")
  echo $PANDOCVERSION
  wget $RELEASES_URL/download/$PANDOCVERSION/pandoc-$PANDOCVERSION-linux.tar.gz
  tar xvzf pandoc-$PANDOCVERSION-linux.tar.gz
  popd
# Download plantuml.jar for plantuml filter
- |
  pushd $HOME
  wget http://sourceforge.net/projects/plantuml/files/plantuml.1.2018.9.jar
  popd
- export PATH=$HOME/pandoc-$PANDOCVERSION/bin:$PATH
- export PLANTUML=$HOME/plantuml.1.2018.9.jar

install: []

script:
- |
  make test

